@startuml
'https://plantuml.com/use-case-diagram

'left to right direction
'(FireBase backend) right of (WorkMate1)

usecase backend as "FireBase backend
==
users fields:
--
id
credentials
favorite places
place to eat today"

package WorkMates {
WorkMate1 -> (backend)
WorkMate2 -> (backend)
WorkMate3 -> (backend)
WorkMate4 -> (backend)
WorkMate5 -> (backend)
}

User -> (backend)




@enduml